# Generated by Django 2.0.7 on 2018-09-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='color_lower',
            new_name='colorLower',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='color_upper',
            new_name='colorUpper',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='position_x',
            new_name='positionX',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='position_y',
            new_name='positionY',
        ),
    ]
